name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Changes

  $CHANGES
categories:
  - title: 'Features'
    labels:
      - 'enhancement'
      - 'breaking'
  - title: 'Bug Fix'
    label: 'bug'
  - title: 'Maintenance Update'
    label: 'maintenance'
  - title: 'Dependency Upgrade'
    label: 'dependency'
exclude-labels:
  - skip_changelog
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'maintenance'
      - 'dependency'
      - 'bug'
  default: patch
