"""empty message

Revision ID: 3c0e2e6006c4
Revises: 
Create Date: 2019-11-14 01:57:53.755735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0e2e6006c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fid_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AC_x', sa.Float(), nullable=True),
    sa.Column('AC_y', sa.Float(), nullable=True),
    sa.Column('AC_z', sa.Float(), nullable=True),
    sa.Column('PC_x', sa.Float(), nullable=True),
    sa.Column('PC_y', sa.Float(), nullable=True),
    sa.Column('PC_z', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fid_db')
    # ### end Alembic commands ###
