"""empty message

Revision ID: 7b4e00130929
Revises: a0928ce2eee6
Create Date: 2021-10-13 16:49:26.122781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b4e00130929"
down_revision = "a0928ce2eee6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flask_dance_oauth", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("provider_user_id", sa.String(length=20), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flask_dance_oauth", schema=None) as batch_op:
        batch_op.drop_column("provider_user_id")

    # ### end Alembic commands ###
