"""empty message

Revision ID: eef891c5c783
Revises: 
Create Date: 2019-11-14 13:59:33.903467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eef891c5c783"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fid_db",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("AC_x", sa.Float(), nullable=True),
        sa.Column("AC_y", sa.Float(), nullable=True),
        sa.Column("AC_z", sa.Float(), nullable=True),
        sa.Column("PC_x", sa.Float(), nullable=True),
        sa.Column("PC_y", sa.Float(), nullable=True),
        sa.Column("PC_z", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fid_db")
    # ### end Alembic commands ###
